jdi-testing/jdn-ai

manifest.json, package.json, src/js/blocks/autoFind/components/autoFind.less, src/js/blocks/autoFind/components/locatorsList/Locator.jsx, src/js/blocks/autoFind/contentScripts/contextMenu/contextmenu.js, src/js/blocks/autoFind/contentScripts/highlight.css, src/js/blocks/autoFind/redux/predictionSlice.js, src/js/blocks/autoFind/utils/scriptListener.js
=> highlight elements on right click and on selection

manifest.json, package.json, src/js/blocks/autoFind/contentScripts/contextMenu/contextmenu.js, src/js/blocks/autoFind/contentScripts/highlight.js, src/js/blocks/autoFind/contentScripts/reportProblemPopup/reportProblemPopup.js, src/js/blocks/autoFind/contentScripts/settingsPopup/settingsPopup.js, src/js/blocks/autoFind/utils/connector.js
При закрытии всей консоли разработчика удалять модалки:
- Report a problem
- settings
- edit name
=> При закрытии плагина убирать со страницы добавленные плагином элементы

manifest.json, package.json, src/js/blocks/autoFind/components/locatorsList/Locator.jsx
https://github.com/jdi-testing/jdn-ai/issues/54
=> Bug fix/us 6 1

manifest.json, package.json, src/js/blocks/autoFind/components/autoFind.less, src/js/blocks/autoFind/components/locatorsList/LocatorsList.jsx
=> make collapse panel sticky

manifest.json, package.json, src/js/blocks/autoFind/components/autoFind.less, src/js/blocks/autoFind/components/locatorsList/LocatorsList.jsx
[1pt][Locators generation is successfully completed] need close this functionally after 10 s
=> BugFix:issue386 was fixed.

manifest.json, package.json, src/js/blocks/autoFind/components/locatorsList/LocatorsList.jsx
https://github.com/jdi-testing/jdn/issues/385
=> BugFix: issue385 was fixed.

manifest.json, package.json, src/css/popups/settingsPopup.less, src/js/blocks/autoFind/components/autoFind.less, src/js/blocks/autoFind/contentScripts/highlight.css, src/js/blocks/autoFind/contentScripts/highlight.js
Проблемы с тултипами были пофикшены https://github.com/jdi-testing/jdn-ai/issues/74 .
=> BugFix: changes for tooltips are made.

manifest.json, package.json, src/common/components/menu/Menu.tsx, src/features/filter/Filter.tsx, src/features/locators/locator/LocatorMenu.tsx, src/features/locators/locatorsPage/LocatorListHeader.jsx, src/features/pageObjects/pageObjList/PageObjMenu.tsx
Deprecated prop `overlay` in `Dropdown` component was replaced as well
https://4x.ant.design/components/dropdown/#header
=> issue_866: Fixed click bubbling in edit PO name modal

manifest.json, package.json, src/common/styles/navigation.less, src/features/locators/components/LocatorsSearch.tsx, src/features/locators/styles/locatorsList.less
Fixed:
- Paddings for the buttons in footer
- Size of search input
=> 946_1020_998: Paddings for the buttons in footer, Size of search input

.prettierrc, manifest.json, package.json, src/features/locators/LocatorsPage.tsx, src/features/locators/components/LocatorEditDialog.tsx, src/features/locators/components/LocatorListHeader.tsx, src/features/locators/components/LocatorsEmptyListInfo.tsx, src/features/locators/text.constants.ts
Closes https://github.com/jdi-testing/jdn-ai/issues/1144
=> Issue 1144 Empty state for Locators List

manifest.json, package.json, src/app/components/OnboardingButton.tsx, src/app/components/ReportProblem.tsx, src/app/components/StatusBar.tsx, src/features/locators/styles/xpath.less, src/features/onboarding/OnboardingProvider.tsx, src/features/onboarding/components/OnboardingPopup.tsx, src/features/onboarding/types/constants.ts, src/features/onboarding/types/context.types.ts, src/features/onboarding/utils/tourSteps.tsx, src/features/pageObjects/components/PageObjMenu.tsx
* UI fixes
* prevent showing onboarding again
=> Issue 1348: small onboarding fixes

manifest.json, package.json
Origin PR is https://github.com/jdi-testing/jdn-ai/pull/1414
=> Issue 1338: small onboarding fixes (version update)

manifest.json, package.json, src/features/locators/utils/locatorOutput.ts
https://github.com/jdi-testing/jdn-ai/issues/1430
Fixed annotation output with xPath + JDI
=> Issue 1430 fix wrong locator output

manifest.json, package.json, src/__tests__/__mocks__/pageObjectMocks/pageObject.mock.js, src/__tests__/pageObject/pageObject.test.js, src/features/pageObjects/utils/hasAnnotationType.ts, src/features/pageObjects/utils/pageObjectTemplate.ts
https://github.com/jdi-testing/jdn-ai/issues/1426
- updated logic to generate pageObjectTemplate for FindBy cases
=> issue 1426 import FindBy for pageObjectTemplate 

manifest.json, package.json, src/features/locators/LocatorsPage.tsx, src/features/onboarding/OnboardingProvider.tsx
https://github.com/jdi-testing/jdn-ai/issues/1427
- added check on page locators before showing EmptyListModal
https://github.com/jdi-testing/jdn-ai/assets/50149163/b280251f-4169-4bae-ba61-e988d0e601f4
=> issue 1427 fix for Empty Page Object 

manifest.json, package.json, src/features/locators/components/LocatorsEmptyListInfo.tsx, src/features/locators/text.constants.ts
https://github.com/jdi-testing/jdn-ai/issues/1144#issuecomment-1669398650
https://github.com/jdi-testing/jdn-ai/assets/50149163/2ab43ffe-7b1a-46b2-a1bf-1747b67025ee
=> Issue 1144 fix empty po messages

manifest.json, package.json, src/__tests__/pageObject/__mocks__/selectLocatorsByPageObject.mock.ts, src/features/locators/reducers/shouldRunGeneration.middleware.ts, src/features/locators/utils/constants.ts, src/features/locators/utils/helpers.ts, src/features/pageObjects/reducers/addPageObject.thunk.js, src/features/pageObjects/selectors/pageObjects.selectors.ts, src/features/pageObjects/types/pageObjectSlice.types.ts, src/pageServices/contentScripts/generationData.js, webpack.config.js
https://github.com/jdi-testing/jdn-ai/issues/1450
Generate All --> xPath --> на страницах с >500 локаторов --> запускает расчет xPath для всех элементов сразу после создания Page Object
+так же исправлено сохранение пунктирной обводки после просчета CSS локаторов
=> Issue 1450

manifest.json, package.json, src/features/locators/types/generationClasses.types.ts, src/features/pageObjects/components/PageObjGenerationBar.tsx
https://github.com/jdi-testing/jdn-ai/issues/1458
=> issue 1458: change order and fix labels in PageObjGenerationBar

manifest.json, package.json, src/features/locators/components/LocatorsTree.tsx, src/features/locators/reducers/runLocatorsGeneration.thunk.ts, src/features/locators/utils/filterLocators.ts, src/features/pageObjects/components/PageObjList.tsx, webpack.config.js
https://github.com/jdi-testing/jdn-ai/issues/1441
=> Issue 1441: fixed xpaths calculation not starting when using a filter

src/features/locators/reducers/runLocatorsGeneration.thunk.ts
https://github.com/jdi-testing/jdn-ai/issues/1441
https://github.com/jdi-testing/jdn-ai/issues/1461
=> fix: use both filter fot clear LS cases

manifest.json, package.json, src/features/onboarding/OnboardingProvider.tsx, src/features/onboarding/types/constants.ts, src/features/onboarding/utils/useOnboardingRef.ts
Updated text for Onboarding Popup text (one text for all dirty cases)
https://github.com/jdi-testing/jdn-ai/issues/1349
=> Issue 1349

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/enhancement.md, .github/ISSUE_TEMPLATE/user-story.md
=> Update issue templates

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/enhancement.md, .github/ISSUE_TEMPLATE/user-story.md
Reverts jdi-testing/jdn-ai#1474
=> Revert "fix: add markdown body type"

manifest.json, package.json, src/__tests__/pageObject/pageObject.test.js, src/features/pageObjects/utils/pageObject.ts, src/features/pageObjects/utils/pageObjectTemplate.ts, src/features/pageObjects/utils/projectTemplate.ts
https://github.com/jdi-testing/jdn-ai/issues/1477
=> Hotfix 1477: Multiple page objects for Vividus

manifest.json, package.json, src/__tests__/__mocks__/pageObjectMocks/pageObject.mock.js, src/features/pageObjects/utils/pageObjectTemplate.ts
https://github.com/jdi-testing/jdn-ai/issues/1480
=> Hotfix 1480: Fixed locator type for Vividus

manifest.json, package.json, src/__tests__/__mocks__/pageObjectMocks/pageObject.mock.js, src/__tests__/pageObject/pageObject.test.js, src/features/pageObjects/utils/pageObject.ts, src/features/pageObjects/utils/pageObjectTemplate.ts, src/features/pageObjects/utils/projectTemplate.ts
Updated minor version of JDN-AI to 3.14
=> Release 3.14

manifest.json, package.json, src/features/locators/components/LocatorEditDialog.tsx, src/features/pageObjects/components/PageObjGenerationBar.tsx
https://github.com/jdi-testing/jdn-ai/issues/1487
=> Issue 1487: Setting FindBy annotation for Vividus

manifest.json, package-lock.json, package.json, src/app/components/StatusBar.tsx, src/app/styles/statusBar.less, src/common/components/Chip.tsx, src/common/components/emptyListInfo/emptyListInfo.less, src/common/components/footnote/Footnote.tsx, src/common/styles/ant.less, src/common/styles/chip.less, src/common/styles/itemsList.less, src/features/filter/Filter.tsx, src/features/filter/components/FilterHeader.tsx, src/features/filter/styles/filter.less, src/features/locators/LocatorsPage.tsx, src/features/locators/styles/locatorEditDialog.less, src/features/onboarding/components/OnboardingPopup.tsx, src/features/onboarding/styles/onboarding.less, src/features/onboarding/styles/onboardingPopup.less, src/features/pageObjects/components/PageObjListHeader.tsx, src/features/pageObjects/styles/pageObject.less, src/features/pageObjects/styles/pageObjectListHeader.less
https://github.com/jdi-testing/jdn-ai/issues/1493
- поправлены съехавшие стили (оступы и тд)
- убранны временные решения
- теперь вместо кастомного компонента для selected items используется Tag из AntD
Заодно поправлены:
- https://github.com/jdi-testing/jdn-ai/issues/1424
- https://github.com/jdi-testing/jdn-ai/issues/1423
=> 1493: AntD fixes

manifest.json, package.json, src/__tests__/__mocks__/pageObjectMocks/pageObject.mock.js, src/features/pageObjects/utils/pageObjectTemplate.ts
https://github.com/jdi-testing/jdn-ai/issues/1489
For xPath:
For CSS:
=> Issue 1489: Vividus template fixed

manifest.json, package.json, src/features/pageObjects/components/PageObjGenerationBar.tsx
https://github.com/jdi-testing/jdn-ai/issues/1490
1. Framework select is disabled: 
2. Correct template is downloaded:
=> Issue 1490: Disable framework select when more than one PO

manifest.json, package.json, src/features/locators/Locator.tsx, src/features/locators/utils/helpers.ts, src/features/locators/utils/locatorOutput.ts, src/features/pageObjects/utils/pageObjectTemplate.ts
https://github.com/jdi-testing/jdn-ai/issues/1496
=> Issue 1496: Vividus html template

manifest.json, package-lock.json, package.json, src/features/onboarding/utils/tourSteps.tsx
https://github.com/jdi-testing/jdn-ai/issues/1407
Updated text on Generate onboarding step.
*Note: Multiline is not supported in default AntD Tour popup*
=> Issue 1407: update text on Generate onboarding step

manifest.json, package-lock.json, package.json, src/app/styles/index.less, src/common/components/CustomConfirm.tsx, src/common/styles/customConfirm.less, src/features/locators/components/LocatorMenu.tsx, src/features/locators/styles/locatorMenu.less
https://github.com/jdi-testing/jdn-ai/issues/1493
=> Issue 1493: styles for CustomModal and Context menu in LocatorList

manifest.json, package-lock.json, package.json, src/common/constants/constants.js, src/features/onboarding/Onboarding.tsx
https://github.com/jdi-testing/jdn-ai/issues/1518
Now the fourth step of onboarding is delayed for one second.
=> Issue 1518

manifest.json, package-lock.json, package.json, src/__tests__/__mocks__/pageObjectMocks/pageObject.mock.js, src/features/pageObjects/utils/pageObjectTemplate.ts
https://github.com/jdi-testing/jdn-ai/issues/1539
=> Issue 1539: Parentheses for URL in Vividus template were removed

.eslintrc.json, manifest.json, package-lock.json, package.json, src/features/locators/Locator.tsx
https://github.com/jdi-testing/jdn-ai/issues/1536
- fixed issues
- updated eslint rules - temporary delete some TS rules
- code refactored according to codestyle
https://github.com/jdi-testing/jdn-ai/assets/50149163/d4b13df8-14f0-4cad-b449-ae1609ec57f8
=> Issue 1536: fix crash after po delete

manifest.json, package-lock.json, package.json, src/features/onboarding/constants.tsx
https://github.com/jdi-testing/jdn-ai/issues/1516
Исправлены тексты, их отображение в онбординге. Добавлен спиннер в шаг генерации локаторов.
=> Issue 1516: onboarding typo

manifest.json, package-lock.json, package.json, src/features/locators/Locator.tsx
https://github.com/jdi-testing/jdn-ai/issues/1567
Исправлен обсчет первого локатора, убрана ошибка рефа онбординга для шагов `ContextMenu`, `AddToPO`
https://github.com/jdi-testing/jdn-ai/assets/50149163/fdbe63ea-ba18-4530-99bc-a0584aaf632b
=> Issue 1567: wrong index for first locator onboarding part

manifest.json, package-lock.json, package.json, src/features/locators/types/generationClasses.types.ts, src/features/pageObjects/components/PageObjGenerationSettings.tsx
Теперь при первом запуске приложения будет предложена HTML5 библиотека по умолчанию.
После выбора любой другой библиотеки - выбор будет сохранен в Local Storage как вариант по умолчанию.
=> Issue 1569:  html library by default

manifest.json, package-lock.json, package.json, src/__tests__/locators/locatorsSlice.test.js, src/features/locators/components/LocatorEditDialog.tsx, src/features/locators/locators.slice.ts, src/features/locators/utils/locatorOutput.tsx, src/features/locators/utils/locatorValidation.ts, src/features/locators/utils/utils.ts, src/pageServices/contentScripts/utils.ts
https://github.com/jdi-testing/jdn-ai/issues/1577
https://github.com/jdi-testing/jdn-ai/issues/1591
- Теперь дропдаун locator type всегда доступен к взаимодействию
- Валидация локатора происходит при переключении дропдауна (и при изменении value в text-aria)
- Поправлена логика создания и сохранения нового локатора (вложенные объекты с атрибутами теперь тоже сохраняются)
- Исправлен баг поиска локаторов из составных классов (`.class1.class2`)
https://github.com/jdi-testing/jdn-ai/assets/50149163/a3eeec31-b95b-4ed3-a112-675a24e07831
=> Issue 1577: locator type dropdown fix state

manifest.json, package-lock.json, package.json, src/common/utils/copyToClipboard.ts, src/features/locators/utils/locatorOutput.tsx
https://github.com/jdi-testing/jdn-ai/issues/1582
https://github.com/jdi-testing/jdn-ai/issues/1589
=> issue 1582: fix output string for locator (qoutes & semicolons)

manifest.json, package-lock.json, package.json, src/app/App.tsx, src/common/utils/localStorage.ts, src/features/onboarding/useOnboarding.tsx
https://github.com/jdi-testing/jdn-ai/issues/1425
Теперь фильтр полностью обнуляется, при запуске онбординга
=> Issue 1425: clear filter setting for onboarding

manifest.json, package-lock.json, package.json, src/features/filter/Filter.tsx, src/features/filter/components/FilterHeader.tsx
https://github.com/jdi-testing/jdn-ai/issues/1581
=> Issue 1581: fix autoclose for filter

manifest.json, package-lock.json, package.json, src/features/onboarding/constants.tsx
- https://github.com/jdi-testing/jdn-ai/issues/1542:
=> Issue 1542: update onboarding texts

manifest.json, package-lock.json, package.json, src/common/styles/itemsList.less
fixes for progress bar position
* https://github.com/jdi-testing/jdn-ai/issues/1482
=> fix: progress bar position

manifest.json, package-lock.json, package.json, src/features/locators/styles/xpath.less
* https://github.com/jdi-testing/jdn-ai/issues/1517
=> Issue 1517: styles for locator icon and checkbox

manifest.json, package-lock.json, package.json, src/features/locators/components/LocatorEditDialog.tsx, src/features/locators/styles/locatorEditDialog.less
* https://github.com/jdi-testing/jdn-ai/issues/1593
=> Issue 1593: replace annotarion select item for edit and create locator

manifest.json, package-lock.json, package.json, src/features/pageObjects/reducers/updateProgressBar.thunk.ts
* https://github.com/jdi-testing/jdn-ai/issues/1622
=> Issue 1622: increase progress bar timer

manifest.json, package-lock.json, package.json, src/app/components/StatusBar.tsx, src/app/reducers/defineServer.thunk.ts, src/app/types/mainSlice.types.ts, src/app/utils/constants.ts, src/features/pageObjects/reducers/updateProgressBar.thunk.ts
* https://github.com/jdi-testing/jdn-ai/issues/1623:
теперь прогресс бар не завершает последний этап, пока не получит ответ с бэкенда
=> Issue 1623: fix progress bar finish logic

manifest.json, package-lock.json, package.json, src/app/store/middlewares/changePage.middleware.ts, src/app/utils/constants.ts, src/pageServices/contentScripts/highlight.js
- https://github.com/jdi-testing/jdn-ai/issues/1636
- changed async logic for progress bar status and navigation to LocatorsLi…st page
=> issue 1636: hightlight box on coverage panel

.github/workflows/release.yml, manifest.json, package-lock.json, package.json
Updated minor version of JDN-AI to 3.15
=> Release 3.15

manifest.json, package-lock.json, package.json, src/app/utils/compatibleVersions.ts, src/features/locators/components/LocatorsTree.tsx
- https://github.com/jdi-testing/jdn-ai/issues/1644
=> Hotfix: issue 1644 scroll behaviour

.eslintrc.json, manifest.json, package-lock.json, package.json, src/features/locators/components/LocatorsTree.tsx, src/features/pageObjects/components/RenamePageObjDialog.tsx, src/features/pageObjects/reducers/addPageObject.thunk.js, src/features/pageObjects/utils/pageObject.ts
* https://github.com/jdi-testing/jdn-ai/issues/1585
=> Issue 1585: fix non unique name for po

manifest.json, package-lock.json, package.json, src/app/main.slice.ts, src/app/reducers/redefineServer.thunk.ts, src/app/reducers/removeAll.thunk.ts, src/app/store/store.ts, src/app/types/mainSlice.types.ts, src/app/utils/appUtils.ts, src/app/utils/hooks/useOnDisconnect.ts, src/common/utils/removeNodesByAttribute.ts, src/features/locators/LocatorsPage.tsx, src/features/locators/components/LocatorMenu.tsx, src/features/locators/reducers/identifyElements.thunk.ts, src/features/locators/reducers/runLocatorsGeneration.thunk.ts, src/features/locators/reducers/stopGeneration.thunk.ts, src/features/locators/reducers/stopGenerationGroup.thunk.ts, src/features/locators/utils/LocatorGenerationController.ts, src/features/locators/utils/runXpathGeneration.ts, src/features/pageObjects/progressBar.slice.ts, src/services/pageDocument/fetchPageDocument.thunk.ts, src/services/pageDocument/pageDocument.reducers.ts, src/services/pageDocument/pageDocument.selectors.ts, src/services/pageDocument/pageDocument.slice.ts, src/services/webSocketController.js, src/services/webSocketMessageHandler.ts
* https://github.com/jdi-testing/jdn-ai/issues/1575
=> Issue 1575: update payload for websockets

manifest.json, package-lock.json, package.json, src/services/backend.ts
- https://github.com/jdi-testing/jdn-ai/issues/1540
=> Issue 1540: change vividus template

manifest.json, package-lock.json, package.json, src/common/styles/variables.less
Lint to the issue: https://github.com/jdi-testing/jdn-ai/issues/1394
=> Issue 1394: Implement Change locator text color

manifest.json, package-lock.json, package.json, src/common/styles/itemsList.less, src/features/locators/LocatorsPage.tsx, src/features/locators/components/LocatorListHeader.tsx, src/features/locators/components/LocatorsEmptyListInfo.tsx, src/features/locators/styles/locatorsList.less, src/features/locators/text.constants.ts, src/features/pageObjects/components/PageObjGenerationSettings.tsx, src/features/pageObjects/components/PageObjListHeader.tsx, src/features/pageObjects/components/PageObjSettingsItem.tsx, src/features/pageObjects/components/PageObjectPlaceholder.tsx, src/features/pageObjects/components/RenamePageObjDialog.tsx, src/features/pageObjects/styles/generationButtons.less, src/features/pageObjects/styles/pageObject.less
- https://github.com/jdi-testing/jdn-ai/issues/1455
=> Issue 1540 small fixes UI

manifest.json, package-lock.json, package.json
- https://github.com/jdi-testing/jdn-ai/issues/1671
=> Issue 1671: rename jdn

manifest.json, package-lock.json, package.json, src/app/types/mainSlice.types.ts, src/app/utils/constants.ts
- https://github.com/jdi-testing/jdn-ai/issues/1664
=> issue 1664: update url for remote connection to back-end

manifest.json, package-lock.json, package.json, src/features/pageObjects/styles/pageObject.less
- https://github.com/jdi-testing/jdn-ai/issues/1529
Before:
After:
=> Issue 1529: pageObject wrong tooltip-arrow position

manifest.json, package-lock.json, package.json, src/app/utils/startsWithDigit.ts, src/features/locators/components/LocatorEditDialog.tsx, src/features/locators/components/utils.ts, src/features/locators/types/locator.types.ts, src/features/locators/utils/createLocatorTypeOptions.tsx, src/features/locators/utils/locatorValidation.ts, src/features/locators/utils/utils.ts
* https://github.com/jdi-testing/jdn-ai/issues/1576
=> Issue 1576: separate logic for edit locator and create custom locator

manifest.json, package-lock.json, package.json, src/features/onboarding/OnboardingProvider.tsx, src/features/onboarding/constants.tsx
Working with chosen Vuetify library:
Working with chosen HTML5:
=> Issue 1541: fix wrong text in onboarding step (Vuetify)

manifest.json, package-lock.json, package.json, src/pageServices/contentScripts/contextmenu.js, src/pageServices/scriptMessageHandler.ts
- https://github.com/jdi-testing/jdn-ai/issues/1495
https://github.com/jdi-testing/jdn-ai/assets/98758686/4f7dd59c-75c6-4da3-abcf-1f54f99fd5b6
=> Issue 1495: fix plugin crash when select 1 element from context menu

manifest.json, package-lock.json, package.json, src/features/locators/styles/locatorList.less
* https://github.com/jdi-testing/jdn-ai/issues/1524
=> Issue 1524: fix styles for locator list

manifest.json, package-lock.json, package.json, src/__tests__/locators/utils/escapeLocatorString.test.ts, src/features/locators/utils/escapeLocatorString.ts, src/features/locators/utils/utils.ts
- https://github.com/jdi-testing/jdn-ai/issues/1655
=> Issue 1655: bug with locator data in edit modal

manifest.json, package-lock.json, package.json, src/features/locators/components/LocatorEditDialog.tsx, src/features/locators/utils/createLocatorTypeOptions.tsx
Issue: https://github.com/jdi-testing/jdn-ai/issues/1701
https://github.com/jdi-testing/jdn-ai/assets/98758686/7d376e11-5a31-4b4a-b22f-df1afef04579
=> Issue 1701: fix locators editing

README.md, manifest.json, package-lock.json, package.json
* https://github.com/jdi-testing/jdn-ai/issues/1706
=> Issue 1706: docs: update readme

manifest.json, package-lock.json, package.json, src/features/locators/components/LocatorsTree.tsx, src/features/locators/utils/escapeLocatorString.ts
Issue: https://github.com/jdi-testing/jdn-ai/issues/1588
Значение меняется на панели и при копировании:
https://github.com/jdi-testing/jdn-ai/assets/98758686/ae3a50bc-1caa-4c57-8e04-8396b9541ff3
=> Issue 1588: escaping special text locator characters

manifest.json, package-lock.json, package.json, src/features/locators/utils/escapeLocatorString.ts, src/features/pageObjects/utils/pageObjectTemplate.ts
Дополнительно к ПР https://github.com/jdi-testing/jdn-ai/pull/1727 :
добавлено экранирование /b символа, а также устранено дополнительное экранирование при скачивании:
=> Issue 1588: escaping special text locator characters (addional fix)

manifest.json, src/features/locators/reducers/identifyElements.thunk.ts, src/pageServices/serviceWorker/background.js, webpack.config.js
* https://github.com/jdi-testing/jdn-ai/issues/1715
=> Issue 1715: fix fetch styles cors policy

manifest.json, package-lock.json, package.json, src/app/App.tsx, src/common/utils/getFullDocumentWithStyles.ts, src/features/locators/selectors/locatorsFiltered.selectors.ts, src/features/locators/utils/LocatorGenerationController.ts, src/features/locators/utils/utils.ts, src/features/pageObjects/utils/pageObject.ts, src/pageServices/scriptMessageHandler.ts
-  temporarily disabled feature css selector calculation and archive template until backend is ready
-  fixed fetching styles from web page
=> Chore: temporarily disable feature css selector calculation and download template 

manifest.json, package-lock.json, package.json, src/app/utils/compatibleVersions.ts
The new compatible version of the back-kend is **0.3.0**
=> fix: update compatible backend version

manifest.json, package-lock.json, package.json
Updated minor version of JDN-AI to 3.16
=> Release 3.16

manifest.json, package-lock.json, package.json, src/pageServices/contentScripts/contextmenu.js
- https://github.com/jdi-testing/jdn-ai/issues/1750
=> Bugfix: page menu

manifest.json, package-lock.json, package.json, src/pageServices/contentScripts/contextmenu.js
- https://github.com/jdi-testing/jdn-ai/issues/1750
=> Bugfix 1750: page menu

manifest.json, package-lock.json, package.json, src/features/pageObjects/styles/pageObject.less
- https://github.com/jdi-testing/jdn-ai/issues/1760
=> Issue 1760: background fixes

manifest.json, package-lock.json, package.json, src/common/utils/getViewportResolution.ts, src/pageServices/pageDataHandlers.ts
- https://github.com/jdi-testing/jdn-ai/issues/1598
=> Issue 1598: pass screen resolution to predict endpoints
